name: my first workflow
on: [push]
jobs:
        show-version:
                runs-on: ubuntu-latest
                steps:
                        - run: python3 --version
                        - run: docker --version
        test-pylint:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                          name: Check the repository
                        - run: |
                                pip install pylint
                                pylint app.py
        build-image-docker:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                          name: Check the repository
                        - run: docker build --tag test-flask-app .
