name: my first workflow
on: [push]
jobs:
        show-version:
                runs-on: ubuntu-latest
                steps:
                        - python --version
                        - docker --version
